// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NYX.Commodities.Services.ProductAPI.Data;

#nullable disable

namespace NYX.Commodities.Services.ProductAPI.Migrations.ProductDB
{
    [DbContext(typeof(ProductDBContext))]
    partial class ProductDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NYX.Commodities.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductColor = "Titanium",
                            ProductDescription = "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit",
                            ProductName = "iPhone 15 Pro",
                            ProductPrice = 999.00m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductColor = "Blue",
                            ProductDescription = "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit",
                            ProductName = "iPhone 15",
                            ProductPrice = 899.00m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductColor = "Silver",
                            ProductDescription = "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit",
                            ProductName = "iPad",
                            ProductPrice = 570.00m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductColor = "Black",
                            ProductDescription = "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit",
                            ProductName = "Mac Pro",
                            ProductPrice = 1300.00m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductColor = "White",
                            ProductDescription = "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit",
                            ProductName = "AirPods",
                            ProductPrice = 260.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
